"""장별 메타데이터 정본. 본문은 chapters/<id>.html에서 관리한다."""

CHAPTERS = (
    {
        'id': 'orientation',
        'title': 'TripPilot 수업의 범위와 준비',
        'source': 'docs/guides/aws-eks-deployment.md',
        'aliases': ('start', 'top'),
        'summary': ('Terraform·Actions·로컬에서 AWS까지, 세 강의를 각 50분으로 진행합니다.', '코드 읽기와 변경 없는 검증은 AWS 계정 없이 학습할 수 있습니다.', 'Cloudflare DNS·동일 digest 승격·plan 이후 승인은 확장 학습입니다.'),
        'notes': '세 강의의 기본 진행 시간은 각 50분입니다. 도구 설치를 사전 과제로 안내하고 30분 수업은 핵심 코드 읽기, 60분 수업은 확장 실습을 포함합니다. 본문과 발표는 같은 장 순서이며 각 슬라이드에서 상세 설명으로 이동할 수 있습니다.',
    },
    {
        'id': 'aws-overview',
        'title': 'TripPilot AWS 전체 구성',
        'source': 'infra/terraform/stack/network.tf',
        'aliases': (),
        'summary': ('VPC 안에 public·private compute·isolated data 서브넷을 둡니다.', 'EKS 앱은 RDS를 사용합니다. Redis는 향후 연결을 위해 준비합니다.'),
        'notes': '큰 경계인 VPC는 우리 서비스의 네트워크 공간입니다. EKS 노드는 private compute에, DB와 캐시는 isolated data에 있습니다. EKS 제어 영역과 ECR·Secrets Manager·CloudWatch는 AWS 관리 서비스로 구분합니다. S3 state와 IAM 역할은 bootstrap이 만듭니다. 그림의 선은 성격에 따라 연결·관리·요청 흐름을 나타냅니다. 정확한 Terraform 참조 관계는 뒤쪽의 ‘도구와 원본 그래프’에서 별도로 봅니다.',
    },
    {
        'id': 'request-path',
        'title': '사용자 요청과 내부 서비스',
        'source': 'deploy/eks/chart/templates/gateway-config.yaml',
        'aliases': (),
        'summary': ('HTTPS 요청은 NLB와 nginx gateway를 거쳐 backend에 도착합니다.', 'backend가 AI를 호출하고 PostgreSQL에 데이터를 저장합니다.', 'AI pgvector 검색과 embedding 연결은 배포 옵션과 별도 데이터 준비를 확인합니다.'),
        'notes': '여기서 gateway는 이 프로젝트의 nginx 애플리케이션 이름입니다. AWS API Gateway 서비스를 뜻하지 않습니다. Expo 모바일 앱은 EKS에 올리지 않습니다. EKS 배포 대상은 gateway, backend, AI, 선택형 embedding입니다. 외부 /internal·Actuator 경로는 gateway가 공개하지 않습니다.',
    },
    {
        'id': 'network-zones',
        'title': '네트워크 구역과 접근 경계',
        'source': 'infra/terraform/stack/network.tf',
        'aliases': (),
        'summary': ('Public은 NLB·NAT, private compute는 EKS, isolated data는 RDS·Redis를 맡습니다.', 'NAT는 내부 앱의 외부 요청에 사용합니다. data subnet에는 인터넷 기본 경로가 없습니다.', 'DB·Redis 접근은 EKS 보안 그룹과 TLS 설정을 함께 확인합니다.'),
        'notes': 'AZ(가용 영역)는 한 리전 안의 분리된 운영 구역입니다. 각 AZ마다 세 종류의 서브넷을 만듭니다. Public이라는 이름만으로 모든 리소스가 외부에 공개되지는 않습니다. 실제 접근은 주소, 경로, 보안 그룹 설정에 달려 있습니다. RDS 5432와 Redis 6379는 EKS 클러스터 보안 그룹에서만 들어오도록 허용하며 TLS를 사용합니다. EKS 노드는 private이지만 관리 API에는 public endpoint도 있습니다.',
    },
    {
        'id': 'ownership',
        'title': '배포 도구별 책임',
        'source': 'docs/guides/aws-eks-deployment.md',
        'aliases': (),
        'summary': ('CloudFormation bootstrap은 state 버킷과 IAM 역할을 준비합니다.', 'Terraform은 AWS 인프라를, Docker와 ECR은 앱 이미지를 관리합니다.', 'Helm의 LoadBalancer Service를 EKS Auto Mode가 읽어 NLB를 만듭니다.'),
        'notes': '이후 Terraform 코드를 읽다가 NLB가 보이지 않아도 빠진 것이 아닙니다. Helm chart의 LoadBalancer Service를 EKS Auto Mode가 읽고 만듭니다. Cloudflare provider와 DNS 생성 리소스는 현재 코드에 없습니다. DNS 자동화는 추가 학습 주제입니다.',
    },
    {
        'id': 'terraform',
        'title': '1강 · Terraform과 Provider',
        'source': 'infra/terraform/stack/versions.tf',
        'aliases': (),
        'summary': ('HCL의 선언·값·의존관계를 읽고 DEV와 PRD의 차이를 설명합니다.', 'Provider는 서비스 API, backend는 state 저장을 담당합니다.', '기본 50분 과정에 Cloudflare 확장 설계와 변경 없는 검증 실습을 포함합니다.'),
        'notes': '1강의 목표와 시간표를 먼저 확인합니다. AWS 리소스 생성은 기본 학생 실습의 완료 조건이 아닙니다. Provider 다운로드의 네트워크 접근과 실제 AWS 리소스 변경을 구분해 안내합니다.',
    },
    {
        'id': 'terraform-concept',
        'title': '원하는 상태와 변경 계획',
        'source': 'infra/terraform/stack/network.tf',
        'aliases': (),
        'summary': ('Terraform은 코드·state·실제 AWS 조회를 비교해 plan을 계산합니다.', '콘솔 변경으로 생긴 차이를 drift라고 부릅니다.', '코드 되돌리기와 DB 데이터 복구는 각각의 절차가 필요합니다.'),
        'notes': '상세 강의의 실제 파일과 예제를 함께 열어 값의 입력과 결과를 추적합니다. 확인 문제는 정답을 먼저 보여 주기 전에 각자의 근거를 설명하게 하고, 구현과 확장 학습의 경계를 확인합니다.',
    },
    {
        'id': 'terraform-map',
        'title': 'Terraform 소스 지도',
        'source': 'infra/terraform/stack/versions.tf',
        'aliases': ('file-map',),
        'summary': ('stack/ 안의 .tf 파일을 함께 평가하고 리소스 참조로 생성 순서를 정합니다.', 'network.tf·eks.tf·data.tf는 네트워크·클러스터·DB와 캐시를 정의합니다.', '변수 검증·환경 입력·outputs·bootstrap 파일까지 이어서 확인합니다.'),
        'notes': 'stack 폴더가 이번 실행의 root module입니다. Terraform의 module은 함께 평가하는 코드 묶음입니다. 이 프로젝트는 외부 VPC 모듈을 호출하지 않고 리소스를 직접 정의합니다. data.tf라는 이름은 여기서 DB·캐시를 묶기 위한 분류이지, data 블록만 담는다는 뜻이 아닙니다.',
    },
    {
        'id': 'terraform-hcl',
        'title': 'HCL 블록과 표현식',
        'source': 'infra/terraform/stack/network.tf',
        'aliases': ('hcl',),
        'summary': ('resource 블록의 유형과 로컬 이름은 실제 AWS 객체의 이름과 구분합니다.', '문자열·숫자·bool·list·map·set의 용도를 코드에서 확인합니다.', 'aws_vpc.this.id 같은 참조로 다른 리소스의 값을 연결합니다.'),
        'notes': '이 문법의 이름은 HCL입니다. 문자열에는 따옴표, true·false와 숫자에는 따옴표를 쓰지 않습니다. resource 뒤의 aws_vpc는 종류, this는 코드에서 참조할 이름입니다. this 자체가 AWS 이름이 되는 것은 아닙니다. aws_vpc.this.id로 AWS가 만든 VPC ID를 읽습니다.',
    },
    {
        'id': 'terraform-values',
        'title': '입력에서 출력까지 값의 흐름',
        'source': 'infra/terraform/stack/variables.tf',
        'aliases': ('values',),
        'summary': ('tfvars와 TF_VAR_ 입력을 variable에서 검증합니다.', 'locals는 환경 이름과 반복 계산을 정리하고 data는 기존 정보를 조회합니다.', 'output은 EKS 이름·ECR 주소·DB 주소를 다음 배포 단계에 전달합니다.'),
        'notes': 'prd.tfvars를 선택하면 같은 코드로 trippilot-prd를 만듭니다. workflow가 -var-file 옵션으로 환경 파일 하나를 지정합니다. AWS 계정 ID와 배포 역할 ARN은 GitHub Environment 변수에서 TF_VAR_ 환경변수로 전달합니다. outputs.tf는 클러스터 이름, ECR 주소, DB 주소 등을 다음 작업에 전달합니다.',
    },
    {
        'id': 'terraform-dependencies',
        'title': '반복 리소스와 의존성',
        'source': 'infra/terraform/stack/network.tf',
        'aliases': ('dependencies', 'repeat'),
        'summary': ('count는 인덱스로, for_each는 안정적인 키로 리소스 주소를 구분합니다.', '직접 참조가 생성 순서를 만들고 숨은 선행 조건에는 depends_on을 씁니다.', '반복 키·순서 변경은 삭제와 교체를 만들 수 있으므로 plan을 읽습니다.'),
        'notes': '직접 참조에서 드러나지 않는 선행 조건은 depends_on으로 적습니다. 이 프로젝트의 EKS는 NAT 경로와 로그 그룹이 준비되기를 기다립니다. graph 원본은 의존하는 자원에서 필요한 자원 쪽으로 선을 그립니다. 전체 AWS 그림의 사용자 요청 방향과 혼동하지 마세요.',
    },
    {
        'id': 'terraform-aws-provider',
        'title': 'AWS Provider의 버전과 인증',
        'source': 'infra/terraform/stack/versions.tf',
        'aliases': (),
        'summary': ('CLI 버전·provider 허용 범위·lockfile의 선택 버전을 나누어 확인합니다.', 'AWS 자격 증명은 실행 환경에서 공급하고 allowed_account_ids로 계정을 제한합니다.', 'fmt·validate와 실제 AWS 권한 검증은 서로 다른 확인입니다.'),
        'notes': 'versions.tf와 .terraform.lock.hcl을 함께 열어 허용 범위와 실제 선택 버전을 비교합니다. 인증 실패와 구성 오류를 구분하고 계정 제한이 왜 필요한지 설명하게 합니다.',
    },
    {
        'id': 'terraform-state',
        'title': 'State와 두 종류의 잠금',
        'source': 'infra/terraform/stack/versions.tf',
        'aliases': ('provider-state',),
        'summary': ('State는 Terraform 주소와 원격 AWS 객체를 연결합니다.', 'S3 backend는 환경별 state와 실행 잠금을 관리합니다.', '.terraform.lock.hcl은 provider 버전을 고정합니다. sensitive도 state 저장을 막지 않습니다.'),
        'notes': 'Backend는 state를 어디에 저장할지 정합니다. AWS provider를 쓴다는 이유만으로 state가 S3에 저장되지는 않습니다. S3 버킷 이름과 리전은 workflow의 init 명령이 전달합니다. 잠금 파일은 동시 수정을 막고, 버전 관리는 이전 state 복구를 돕습니다. State에는 민감한 정보가 들어갈 수 있으므로 공개하지 않습니다. sensitive 표시만으로 저장 자체를 막을 수는 없습니다.',
    },
    {
        'id': 'terraform-bootstrap',
        'title': 'Terraform 실행 전 초기 기반',
        'source': 'infra/bootstrap/template.json',
        'aliases': (),
        'summary': ('관리자가 GitHub OIDC 신뢰와 bootstrap 실행 권한을 먼저 준비합니다.', 'CloudFormation이 환경별 state 버킷과 Terraform·EKS IAM 역할을 만듭니다.', '최초 권한을 만드는 단계와 일상 배포 단계를 구분합니다.'),
        'notes': '상세 강의의 실제 파일과 예제를 함께 열어 값의 입력과 결과를 추적합니다. 확인 문제는 정답을 먼저 보여 주기 전에 각자의 근거를 설명하게 하고, 구현과 확장 학습의 경계를 확인합니다.',
    },
    {
        'id': 'terraform-environments',
        'title': 'DEV와 PRD의 운영 조건',
        'source': 'infra/terraform/environments/prd.tfvars',
        'aliases': ('environments',),
        'summary': ('DEV는 2 AZ·NAT 1개·RDS Single-AZ·Redis 1노드를 사용합니다.', 'PRD는 3 AZ·NAT 3개·RDS Multi-AZ·Redis 3노드와 삭제 보호를 사용합니다.', 'State·VPC·도메인을 환경별로 구분하고 가용성과 비용을 함께 비교합니다.'),
        'notes': '3 AZ라고 PostgreSQL을 3개 만든다는 뜻은 아닙니다. 이 코드는 RDS DB instance의 Multi-AZ를 켭니다. Redis는 primary 1개와 replica 2개입니다. EKS 노드 수는 Auto Mode가 워크로드에 맞게 관리하므로 고정 숫자로 가르치지 않습니다. DEV의 공유 NAT는 비용을 줄이는 대신 한 NAT에 의존합니다. 같은 AWS 계정에서 환경을 분리해도 완전한 권한 격리가 되지는 않습니다.',
    },
    {
        'id': 'terraform-cloudflare',
        'title': '확장 예제 · Cloudflare DNS',
        'source': 'infra/terraform/stack/versions.tf',
        'aliases': (),
        'summary': ('현재 저장소에는 Cloudflare provider와 DNS 자동화가 없습니다.', '확장 예제는 Cloudflare v5의 DNS CNAME으로 API 도메인을 NLB에 연결합니다.', 'ACM 검증 레코드와 API 접속 레코드의 역할을 구분합니다.'),
        'notes': '이 장은 Cloudflare v5 확장 예제입니다. 저장소에 이미 적용된 자동화로 설명하지 않습니다. 인증서 검증용 레코드와 API 접속용 레코드를 학생이 각각 그려 보게 합니다.',
    },
    {
        'id': 'terraform-lab',
        'title': '실습 · AWS 변경 없는 Terraform 검증',
        'source': 'infra/terraform/stack/tests/environments.tftest.hcl',
        'aliases': ('terraform-commands', 'read-plan', 'local-terraform-lab'),
        'summary': ('fmt 후 backend를 끈 init·validate·mock provider test를 실행합니다.', '잠금 파일을 유지하고 실패 입력이 실제로 거부되는지 확인합니다.', '실제 plan의 삭제·교체와 AWS 권한은 별도 환경에서 확인합니다.'),
        'notes': '권한, 계정 제한, 서비스 할당량, 실제 리전 지원 여부 등은 AWS와 연결해야 확인할 수 있습니다. apply는 자원을 만들고 비용을 발생시킬 수 있습니다. 수업의 로컬 단계에서는 실제 AWS를 변경하지 않고, 실제 변경은 환경 준비 후 Actions에서 수행합니다.',
    },
    {
        'id': 'terraform-check',
        'title': '확인 · 인프라 설계 설명하기',
        'source': 'infra/terraform/stack/variables.tf',
        'aliases': (),
        'summary': ('PRD 2 AZ와 single_nat_gateway=true가 왜 거부되는지 설명합니다.', 'Provider·backend·state·lockfile이 맡는 일을 구분합니다.', 'Cloudflare DNS 연결이 현재 구현인지 확장 예제인지 판단합니다.'),
        'notes': '파일을 실제로 바꾸지 않고 답을 예상해도 됩니다. 이어서 “PRD에서 single_nat_gateway=true도 될까요?”라고 물어보세요. 이것도 검증이 거부합니다. 이 규칙이 있어서 실수하기 쉬운 설계 조건을 코드로 유지할 수 있습니다.',
    },
    {
        'id': 'actions',
        'title': '2강 · GitHub Actions',
        'source': '.github/workflows/aws-deploy.yml',
        'aliases': (),
        'summary': ('Workflow는 이벤트, job, step으로 배포의 실행 순서를 표현합니다.', 'TripPilot AWS 배포는 workflow_dispatch로 수동 시작합니다.', '검증·권한·환경 보호·동시 실행의 경계를 실제 YAML로 읽습니다.'),
        'notes': 'Runner는 작업을 실행하는 컴퓨터입니다. workflow 하나에 여러 job이 있고, job 안의 step은 순서대로 실행합니다. 서로 다른 job은 기본적으로 별도 실행 환경이므로 작업 폴더가 자동 공유되지 않습니다. uses는 준비된 action을 쓰고, run은 셸 명령을 실행합니다.',
    },
    {
        'id': 'actions-objectives',
        'title': '2강 진행표와 학습 목표',
        'source': '.github/workflows/aws-deploy.yml',
        'aliases': (),
        'summary': ('기본 50분 동안 YAML·값 전달·validate·deploy·OIDC를 다룹니다.', '연습 workflow로 needs·outputs·조건 실행을 확인합니다.', '30분 과정은 핵심 코드 읽기, 60분 과정은 승인·동시성 토론을 확장합니다.'),
        'notes': '30분·50분·60분 편성의 실습 범위는 상세 강의의 시간표를 사용합니다. 도구 설치와 다운로드를 사전 과제로 안내해 코드 읽기에 집중할 시간을 확보합니다.',
    },
    {
        'id': 'actions-model',
        'title': '이벤트와 실행 경로',
        'source': '.github/workflows/aws-deploy.yml',
        'aliases': ('ci-vs-deploy',),
        'summary': ('기존 애플리케이션 CI와 AWS 수동 배포는 별도의 workflow입니다.', 'develop의 GHCR 이미지가 ECR로 자동 복사되거나 AWS 배포를 시작하지 않습니다.', 'PR 브랜치 필터는 대상 브랜치이며 경로 필터와 함께 적용됩니다.'),
        'notes': '기존 CI는 develop push, develop/main 대상 PR, 수동 실행을 지원합니다. GHCR 이미지가 ECR로 자동 복사되는 구조가 아닙니다. AWS workflow에는 자체 validate job이 있지만 기존 CI 성공을 필수로 연결하는 needs 관계는 없습니다. PRD도 DEV에서 만든 이미지를 그대로 승격하는 기능 없이 선택한 소스를 다시 빌드합니다.',
    },
    {
        'id': 'actions-yaml',
        'title': 'YAML과 Job·Step',
        'source': '.github/workflows/aws-deploy.yml',
        'aliases': ('uses-run',),
        'summary': ('uses는 action을 호출하고 run은 runner에서 셸 명령을 실행합니다.', 'needs는 job의 순서를, if는 실행 조건을 정의합니다.', '완전한 연습 예제로 YAML 들여쓰기와 출력 연결을 확인합니다.'),
        'notes': '위 예제는 실제 workflow에서 중간 도구 설치 단계를 생략한 발췌입니다. 그대로 새 workflow로 복사하는 완성 예제가 아닙니다. setup-terraform step이 먼저 Terraform CLI를 설치해야 run의 명령을 사용할 수 있습니다.',
    },
    {
        'id': 'actions-data',
        'title': 'Actions 값의 범위',
        'source': 'infra/scripts/workflow_config.py',
        'aliases': (),
        'summary': ('inputs·vars·secrets·env·outputs는 서로 다른 역할과 범위를 가집니다.', 'GITHUB_OUTPUT은 step 결과, GITHUB_ENV는 같은 job의 후속 step 값을 전달합니다.', '서로 다른 job의 파일은 자동 공유되지 않으므로 필요한 결과를 명시합니다.'),
        'notes': '상세 강의의 실제 파일과 예제를 함께 열어 값의 입력과 결과를 추적합니다. 확인 문제는 정답을 먼저 보여 주기 전에 각자의 근거를 설명하게 하고, 구현과 확장 학습의 경계를 확인합니다.',
    },
    {
        'id': 'actions-validate',
        'title': 'AWS 접근 전 검증 Job',
        'source': '.github/workflows/aws-deploy.yml',
        'aliases': ('jobs',),
        'summary': ('Python 테스트·coverage·bootstrap 정책·chart 검사·Helm lint를 실행합니다.', 'Terraform fmt·validate·mock test가 인프라 설계 조건을 검사합니다.', 'validate가 성공한 뒤 deploy가 시작됩니다. AWS 실제 동작은 별도 검증합니다.'),
        'notes': 'validate는 Python 테스트와 coverage, bootstrap/chart 검사, Helm lint, Terraform fmt·validate·mock test를 수행합니다. apply와 앱 배포를 함께 선택하면 backend 종료 설정 테스트도 추가됩니다. Environment에 required reviewers를 설정했다면 deploy job 시작 전에 승인을 받습니다. 이는 그 실행에서 아직 만들지 않은 plan을 승인하는 단계는 아닙니다.',
    },
    {
        'id': 'actions-deploy',
        'title': 'Deploy Job의 입출력',
        'source': '.github/workflows/aws-deploy.yml',
        'aliases': ('manual-inputs', 'images', 'secrets-db', 'helm'),
        'summary': ('환경·mode·deploy_application·embedding_enabled 입력을 먼저 검증합니다.', 'OIDC 인증 후 plan·apply, Docker build·ECR 발행 순서로 진행합니다.', 'Secret 동기화와 DB 준비가 성공한 뒤 Helm 배포와 내부 smoke를 수행합니다.'),
        'notes': 'mode 기본값은 plan, deploy_application 기본값은 true, embedding_enabled 기본값은 false입니다. workflow_config.py가 조합을 검사하여 실제 앱 배포 여부를 결정합니다. 임베딩을 활성화하면 메모리 비용이 늘어납니다. AWS 변경은 수동 입력으로만 시작합니다.',
    },
    {
        'id': 'actions-security',
        'title': 'GitHub OIDC와 AWS 권한',
        'source': 'infra/bootstrap/template.json',
        'aliases': ('oidc',),
        'summary': ('id-token: write는 GitHub 신원 토큰을 요청할 권한입니다.', 'STS가 IAM 역할의 신뢰 정책을 확인하고 임시 자격 증명을 발급합니다.', 'Environment subject와 배포 브랜치 제한, AWS 권한 정책을 함께 적용합니다.'),
        'notes': 'deploy job의 id-token: write는 OIDC 토큰 요청 권한입니다. 그것만으로 AWS 작업 권한이 생기지는 않습니다. AWS_ROLE_ARN으로 지정한 IAM 역할의 신뢰 정책과 권한 정책을 통과해야 합니다. Environment 기반 subject에는 브랜치가 포함되지 않으므로 GitHub Environment의 배포 브랜치 제한도 설정합니다.',
    },
    {
        'id': 'actions-environment',
        'title': 'Environment 승인과 Plan 검토',
        'source': '.github/workflows/aws-deploy.yml',
        'aliases': (),
        'summary': ('Environment 승인은 deploy job이 시작되기 전에 일어납니다.', '현재 실행의 plan이 생성된 뒤 다시 승인받는 단계는 없습니다.', '저장한 plan 검토 후 승인하려면 job 분리와 안전한 artifact 관리가 추가로 필요합니다.'),
        'notes': 'Environment 승인 화면이 나타나는 시점과 terraform plan step 실행 시점을 나란히 확인합니다. 생성되지 않은 plan을 검토했다고 기록하는 실수를 예방하는 것이 핵심입니다.',
    },
    {
        'id': 'actions-concurrency',
        'title': '동시 실행과 State 잠금',
        'source': '.github/workflows/aws-deploy.yml',
        'aliases': (),
        'summary': ('환경별 concurrency group은 같은 환경의 배포가 겹치지 않도록 직렬화합니다.', 'Terraform state 잠금은 다른 실행 경로의 동시 변경도 방지합니다.', '잠금이 남으면 실행 중인 작업을 먼저 확인하고 강제 해제를 판단합니다.'),
        'notes': '상세 강의의 실제 파일과 예제를 함께 열어 값의 입력과 결과를 추적합니다. 확인 문제는 정답을 먼저 보여 주기 전에 각자의 근거를 설명하게 하고, 구현과 확장 학습의 경계를 확인합니다.',
    },
    {
        'id': 'actions-lab',
        'title': '실습 · 실행 순서와 실패 경계',
        'source': '.github/workflows/aws-deploy.yml',
        'aliases': (),
        'summary': ('연습 YAML에서 validate·report job의 의존성과 출력을 연결합니다.', '실패한 선행 job 뒤의 실행 여부를 예상하고 로그로 확인합니다.', 'AWS 자격 증명 없이 저장소의 정책 테스트만 실행합니다.'),
        'notes': '상세 강의의 실제 파일과 예제를 함께 열어 값의 입력과 결과를 추적합니다. 확인 문제는 정답을 먼저 보여 주기 전에 각자의 근거를 설명하게 하고, 구현과 확장 학습의 경계를 확인합니다.',
    },
    {
        'id': 'actions-review',
        'title': '확인 · 자동화의 책임 설명하기',
        'source': '.github/workflows/aws-deploy.yml',
        'aliases': (),
        'summary': ('Job 간 파일 전달과 step output 전달의 차이를 설명합니다.', 'OIDC 토큰 요청 권한과 AWS 리소스 권한을 구분합니다.', 'Environment 승인 시점과 실행 중단의 영향을 실제 코드로 답합니다.'),
        'notes': '상세 강의의 실제 파일과 예제를 함께 열어 값의 입력과 결과를 추적합니다. 확인 문제는 정답을 먼저 보여 주기 전에 각자의 근거를 설명하게 하고, 구현과 확장 학습의 경계를 확인합니다.',
    },
    {
        'id': 'release',
        'title': '3강 · 로컬에서 DEV·PRD까지',
        'source': 'docs/guides/aws-eks-deployment.md',
        'aliases': (),
        'summary': ('로컬 kind에서 앱을 확인한 뒤 AWS 초기 기반과 환경 설정을 준비합니다.', 'DEV plan·인프라·이미지·앱 배포 후 내부와 외부 경로를 검사합니다.', 'PRD 배포와 동일 digest 승격 확장, 실패 조사·복구 범위를 다룹니다.'),
        'notes': '상세 강의의 실제 파일과 예제를 함께 열어 값의 입력과 결과를 추적합니다. 확인 문제는 정답을 먼저 보여 주기 전에 각자의 근거를 설명하게 하고, 구현과 확장 학습의 경계를 확인합니다.',
    },
    {
        'id': 'release-map',
        'title': '배포 단계와 결과물',
        'source': 'docs/guides/aws-eks-deployment.md',
        'aliases': (),
        'summary': ('로컬 검증·bootstrap·Terraform·이미지 빌드·Helm 배포의 결과를 연결합니다.', '로컬 Bazel 이미지 경로와 AWS Dockerfile 빌드 경로를 구분합니다.', '현재 DEV와 PRD는 각각 소스를 다시 빌드합니다.'),
        'notes': '상세 강의의 실제 파일과 예제를 함께 열어 값의 입력과 결과를 추적합니다. 확인 문제는 정답을 먼저 보여 주기 전에 각자의 근거를 설명하게 하고, 구현과 확장 학습의 경계를 확인합니다.',
    },
    {
        'id': 'release-local',
        'title': '실습 A · 로컬 배포 후보',
        'source': 'deploy/README.md',
        'aliases': ('local-to-prd',),
        'summary': ('just doctor로 도구를 확인하고 kind·Helm으로 로컬 환경을 띄웁니다.', 'backend·AI·gateway와 DB migration·health 경로를 확인합니다.', '로컬 성공은 IAM·RDS·NLB·실제 DNS 검증을 대신하지 않습니다.'),
        'notes': '로컬은 Docker, kind, kubectl, Helm, Bazel, JDK 등의 도구가 필요하며 just doctor로 확인합니다. just up은 로컬 자원을 만들므로 준비된 개발 환경에서 실행합니다. kind가 통과해도 IAM·RDS·NLB까지 검증한 것은 아닙니다. PRD에서는 Environment 보호 설정과 선택 브랜치를 확인하고, 배포 후 이미지 태그와 실제 API 상태를 기록합니다.',
    },
    {
        'id': 'release-bootstrap',
        'title': '최초 설정과 GitHub Environment',
        'source': 'docs/guides/aws-bootstrap.md',
        'aliases': ('bootstrap', 'github-settings'),
        'summary': ('dev와 prd Environment에 계정·역할·state·도메인 변수를 나누어 설정합니다.', 'Bootstrap 권한과 일반 배포 역할, 배포 브랜치 제한을 확인합니다.', 'AWS 관리자 준비 후 환경별 bootstrap workflow를 실행합니다.'),
        'notes': '아무 AWS 권한이 없는 workflow가 자신의 최초 권한을 만들 수는 없습니다. 그래서 관리자 설정과 bootstrap이 먼저입니다. 환경별 최초 설정 후에는 일반 배포 workflow를 사용합니다. bootstrap을 다시 실행하면 CloudFormation stack을 갱신합니다. bootstrap 역할은 권한 위임을 다루므로 일반 배포 역할과 구분해서 관리합니다.',
    },
    {
        'id': 'release-dev',
        'title': '실습 B · DEV 인프라와 앱',
        'source': 'docs/guides/aws-eks-deployment.md',
        'aliases': ('deploy-plan', 'apply-infrastructure'),
        'summary': ('첫 실행은 dev + plan으로 계정·환경·삭제·교체 항목을 확인합니다.', 'apply는 같은 실행에서 만든 plan을 적용합니다. Secret·인증서 준비를 확인합니다.', '앱 배포는 Docker 이미지 발행·DB 준비·Helm·smoke 결과까지 확인합니다.'),
        'notes': '처음에는 기존 data source인 cluster/node IAM 역할도 조회하므로 bootstrap이 완료되어 있어야 합니다. plan은 AWS 자원을 생성하지 않지만 조회와 state 잠금을 사용합니다. required reviewers가 있어도 새 plan 생성 이후에 한 번 더 멈추는 승인 단계는 현재 구현되어 있지 않습니다.',
    },
    {
        'id': 'release-network',
        'title': '실습 C · 내부와 외부 연결',
        'source': 'deploy/eks/chart/templates/services.yaml',
        'aliases': ('dns-check',),
        'summary': ('클러스터 내부 smoke와 실제 도메인의 DNS·TLS 검증을 각각 수행합니다.', '같은 리전의 ACM 인증서를 준비하고 API 도메인을 NLB 주소에 연결합니다.', '외부 /healthz와 업무 API를 확인합니다. internal·Actuator는 공개하지 않습니다.'),
        'notes': 'ACM 인증서는 앱 배포 전에 같은 리전·계정에서 발급하고 DNS 검증을 마쳐야 합니다. 앱 배포 후에는 API 도메인을 새 NLB 주소에 연결합니다. 인증서 검증용 DNS 레코드와 API 접속용 DNS 레코드는 역할이 다릅니다. workflow의 내부 smoke 통과만으로 외부 DNS가 올바르다고 판단할 수 없습니다.',
    },
    {
        'id': 'release-prd',
        'title': '현재 구현의 PRD 배포',
        'source': 'docs/guides/aws-eks-deployment.md',
        'aliases': (),
        'summary': ('PRD 브랜치·계정·Environment 보호·state 경로를 다시 확인합니다.', 'PRD는 선택한 소스를 재빌드하며 DEV 이미지 digest를 자동 승격하지 않습니다.', '실행 SHA·이미지 tag·Helm 상태·실제 API 결과를 배포 기록에 남깁니다.'),
        'notes': '상세 강의의 실제 파일과 예제를 함께 열어 값의 입력과 결과를 추적합니다. 확인 문제는 정답을 먼저 보여 주기 전에 각자의 근거를 설명하게 하고, 구현과 확장 학습의 경계를 확인합니다.',
    },
    {
        'id': 'release-promotion',
        'title': '확장 설계 · 동일 Digest 승격',
        'source': 'deploy/eks/chart/values.schema.json',
        'aliases': (),
        'summary': ('한 번 빌드한 이미지 digest를 검증한 뒤 DEV와 PRD에 전달하는 제안입니다.', 'Workflow·runtime·Helm schema/helper·IAM을 함께 변경해야 합니다.', '현재 구현에 없는 기능이므로 예제와 적용 가능한 명령을 구분합니다.'),
        'notes': 'digest 승격은 현재 workflow의 동작이 아닌 제안 설계입니다. 상세 강의의 코드 예제와 변경 대상 목록을 함께 읽고 tag 불변성과 빌드 동일성이 다른 성질임을 확인합니다.',
    },
    {
        'id': 'release-recovery',
        'title': '실패 조사와 복구 범위',
        'source': 'deploy/eks/runtime.py',
        'aliases': ('troubleshooting', 'rollback'),
        'summary': ('처음 실패한 step과 올바른 계정·클러스터·배포 revision을 확인합니다.', 'Helm --atomic은 Helm 명령 실패를 다룹니다. 이후 smoke 실패는 별도 판단합니다.', 'Terraform 변경·DB migration·데이터 복구에는 각각 복구 계획이 필요합니다.'),
        'notes': '로그를 공유할 때 비밀값을 포함하지 않습니다. EKS Pod 조회는 올바른 계정·리전·클러스터 컨텍스트인지 먼저 확인합니다. 상태 잠금이 남아 있다고 곧바로 강제 해제하지 말고 같은 환경에서 실행 중인 배포가 있는지 확인합니다.',
    },
    {
        'id': 'release-review',
        'title': '확인 · 한 페이지 배포 기록',
        'source': 'docs/guides/aws-eks-deployment.md',
        'aliases': ('review',),
        'summary': ('실제 구현과 확장 설계, 로컬 검증과 AWS 검증을 구분해 설명합니다.', 'Image 출처·동일성, 내부 smoke·외부 TLS, 복구 경계를 기록합니다.', '비밀값을 제외하고 명령·결과·대상 SHA를 제출합니다.'),
        'notes': '추가 과제: 구성도에서 Terraform이 만들지 않는 항목 3개 찾기, DEV와 PRD 차이 3개 설명하기, 수동 배포 로그에서 각 단계의 시작점을 찾기. 실제 AWS를 생성하지 않아도 코드와 자료만으로 수행할 수 있습니다.',
    },
    {
        'id': 'diagram-tools',
        'title': '구성도의 출처와 재생성',
        'source': 'docs/education/assets/README-diagrams.md',
        'aliases': (),
        'summary': ('Terraform graph와 Graphviz로 실제 의존성 원본을 보존합니다.', '발표용 구성도는 HCL·환경값·Helm·bootstrap 경계를 읽은 교육용 재배치입니다.', 'SHA-256 출처와 재생성 방법을 확인합니다. AWS 계정 실측도가 아닙니다.'),
        'notes': 'Rover와 InfraMap 등도 검토했으며, 이 자료에서는 배포 전 코드만으로 로컬에서 재생성할 수 있는 Terraform 공식 graph와 Graphviz를 선택했습니다. graph는 네트워크 패킷 흐름이나 실제 AZ 배치를 자동 확정하는 도구가 아닙니다. 발표용 생성기는 이 저장소 구조에 맞춘 해석을 적용하므로 변경한 코드는 생성 방법 문서와 함께 검토합니다.',
    },
    {
        'id': 'appendix',
        'title': '수업 후 기록과 참고 자료',
        'source': 'docs/guides/aws-eks-deployment.md',
        'aliases': ('references',),
        'summary': ('변경 SHA·환경·권한·인프라 plan·이미지·검증·복구를 기록합니다.', '실제 배포를 하지 않았다면 예제 로그 또는 예상값이라고 표시합니다.', '저장소의 운영 가이드와 코드, 장별 공식 문서 링크를 함께 확인합니다.'),
        'notes': '이 자료는 저장소의 Terraform과 workflow를 기준으로 작성했습니다. AWS 계정에 배포한 결과를 보증하는 운영 기록은 아닙니다. Cloudflare DNS 자동화, 동일 이미지 digest를 DEV에서 PRD로 승격하기, plan 생성 후 별도 승인하기는 현재 구현 범위 밖의 추가 학습 주제입니다.',
    },
)
