apiVersion: v1
kind: Service
metadata:
  name: ai
  namespace: trippilot
spec:
  selector:
    app: ai
  ports:
    - name: http
      port: 8000
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: ai-nodeport
  namespace: trippilot
spec:
  type: NodePort
  selector:
    app: ai
  ports:
    - name: http
      port: 8000
      targetPort: http
      nodePort: 30082
