-- 아웃박스 봉투에 스키마 버전을 실는다(TRIP-539).
--
-- `EventEnvelope` 는 처음부터 `schemaVersion` 을 들고 있었는데(진화 대비) V1.0 테이블에 그 칸이 없다.
-- 지금까지는 아무도 아웃박스에 쓰지 않아 드러나지 않았다 — 적재를 붙이는 이 시점에 맞춘다.
--
-- payload JSON 안에 넣지 않는 이유: **조회로 거를 수 없다.** 스키마가 갈렸을 때 "구버전 행만"을
-- 찾아야 하는데 jsonb 안이면 인덱스도 못 태운다. 나중에 컬럼을 추가하면 기존 행이 비어 버린다.
--
-- ⚠ V2.28 은 U5·U6 설계 문서가 `visit_photo_meta` 로 제안한 번호이기도 하다. 그쪽은 아직
-- 코드가 없고 문서도 "머지 시점 재배정"을 명시했다 — 실제로 먼저 머지되는 이 쪽이 번호를 갖는다.
ALTER TABLE outbox_event ADD COLUMN schema_version int NOT NULL DEFAULT 1;
